### ISSUE TITLE
[Fabric 1.19.2] Game crashes before loading

### ISSUE THREAD

**Issue by Nekkok** [Skylortrexler/Difficultyplus#9]
I don't understand why, so maybe you should take a look yourself. Thank you, I love your mod as is pretty balanced and doesn't cluster everything with flashy not-so-vanillish features <3

[crash-2023-01-22_13.03.49-client.txt](https://github.com/skylorbeck/Difficultyplus/files/10474383/crash-2023-01-22_13.03.49-client.txt)

**Comment by skylorbeck** [comment]
It looks like you are missing my library, SkyLib.

**Comment by Nekkok** [comment]
Oh yes! I'm sorry I didn't notice. Thank you!
